export const Members = [
    {
        name: "Ginger Club",
        limited: "Limited (55 of 55 remaining)",
        amount: " $5 ",
        month: "PER MONTH",
        discr: "This club is for those who want to level-up by supporting the work.You like the chai (the content), and you want more.",
        list: "Access to members-only Discord",
        list1: " Discounts on merch and paid extras",
        list2: "Unlock exclusive posts and messages",
        list3: "Support me on a monthly basis",
    },
    {
        name: "Cinnamon Club",
        limited: "Limited (25 of 25 remaining)",
        amount: " $15 ",
        month: "PER MONTH",
        discr: "This is for you if you're curious about the thinking, processing, that goes into the 'chai.' You get all the Ginger club benefits and..",
        list: "Access to members-only YouTube livestreams",
        list1: " Access to full, uncut, versions of my teachings, Q&As, podcast appearances, & studies",
        list2: "Behind-the-scenes access to my systems and content creation workflow",
        list3: " Support me on a monthly basis",
    },
    {
        name: "Cardamom Club",
        limited: "Limited (15 of 15 remaining) ",
        amount: " $20 ",
        month: "PER MONTH",
        discr: "This is for you if you want to have literal chai with me and other people periodically. You get all Ginger club and Cinnamon club benefits and.....",
        list: "Monthly ZOOM chai session with the Cardamom Squad",
        list1: "Support me on a monthly basis",
        list2: "",
        list3: "",
    },
];
